exports.users = [
  {
    name: "John Smith",
    email: "john.smith@example.com",
    password: "john1234",
    phone: "01712345678",
    address: "Dhaka",
  },
  {
    name: "sarah jones",
    email: "SARAH.JONES@GMAIL.COM",
    password: "sarah!456",
    phone: "01898765432",
    address: "Chittagong",
  },
  {
    name: "Mike Chen",
    email: "mike.chen@yahoo.com",
    password: "mikePass123",
    phone: "01911223344",
    address: "Sylhet",
    isAdmin: true,
  },
  {
    name: "EMILY WILSON",
    email: "emily_wilson@hotmail.com",
    password: "emily@789",
    phone: "01655667788",
    address: "Khulna",
  },
  {
    name: "alexander brown",
    email: "alex.brown@outlook.com",
    password: "alexBrown!",
    phone: "01512349876",
    address: "Rajshahi",
    isBanned: true,
  },
  {
    name: "Lisa Garcia",
    email: "lisa.garcia@company.com",
    password: "lisaG2024",
    phone: "01744556677",
    address: "Barisal",
  },
  {
    name: "DAVID MILLER",
    email: "david.miller@tech.org",
    password: "davidM1ller",
    phone: "01877889900",
    address: "Rangpur",
    isAdmin: true,
  },
  {
    name: "sophia martinez",
    email: "sophia_martinez@edu.bd",
    password: "sophia!123",
    phone: "01900112233",
    address: "Comilla",
  },
  {
    name: "Robert Taylor",
    email: "robert.taylor@business.com",
    password: "robertTay",
    phone: "01633445566",
    address: "Narayanganj",
    isBanned: true,
  },
  {
    name: "MARY JOHNSON",
    email: "mary.johnson@service.net",
    password: "maryJ2024",
    phone: "01766778899",
    address: "Gazipur",
  },
  {
    name: "kevin lee",
    email: "kevin_lee@startup.io",
    password: "kevinLee#1",
    phone: "01899001122",
    address: "Mymensingh",
    isAdmin: true,
  },
  {
    name: "Amanda White",
    email: "amanda.white@design.co",
    password: "amandaWht",
    phone: "01922334455",
    address: "Dinajpur",
  },
  {
    name: "CHRISTOPHER DAVIS",
    email: "chris.davis@music.org",
    password: "chrisD@456",
    phone: "01677889900",
    address: "Bogra",
  },
  {
    name: "jennifer lopez",
    email: "jennifer.lopez@entertainment.com",
    password: "jennyL0pez",
    phone: "01788990011",
    address: "Jessore",
    isBanned: true,
  },
  {
    name: "Daniel Kim",
    email: "daniel.kim@techcorp.com",
    password: "danielK!m",
    phone: "01811223344",
    address: "Pabna",
  },
  {
    name: "michelle wong",
    email: "MICHELLE.WONG@ASIA.COM",
    password: "michelleW",
    phone: "01933445566",
    address: "Kushtia",
    isAdmin: true,
  },
  {
    name: "James Anderson",
    email: "james.anderson@uk.co",
    password: "jamesAnd1",
    phone: "01644556677",
    address: "Faridpur",
  },
  {
    name: "PATRICIA THOMAS",
    email: "patricia.thomas@canada.ca",
    password: "patriciaT",
    phone: "01755667788",
    address: "Tangail",
  },
  {
    name: "ryan patel",
    email: "ryan_patel@india.in",
    password: "ryanP@tel",
    phone: "01866778899",
    address: "Noakhali",
    isBanned: true,
  },
  {
    name: "Jessica Scott",
    email: "jessica.scott@australia.au",
    password: "jessicaS1",
    phone: "01977889900",
    address: "Chandpur",
  },
  {
    name: "BRIAN ROBINSON",
    email: "brian.robinson@europe.eu",
    password: "brianRob!",
    phone: "01688990011",
    address: "Lakshmipur",
    isAdmin: true,
  },
  {
    name: "ashley hall",
    email: "ashley.hall@student.edu",
    password: "ashleyH@2",
    phone: "01799001122",
    address: "Feni",
  },
  {
    name: "Matthew Clark",
    email: "matthew.clark@developer.dev",
    password: "mattClark",
    phone: "01800112233",
    address: "Brahmanbaria",
  },
  {
    name: "REBECCA YOUNG",
    email: "rebecca.young@teacher.org",
    password: "rebeccaY1",
    phone: "01911224455",
    address: "Shariatpur",
    isBanned: true,
  },
  {
    name: "steven king",
    email: "steven_king@writer.com",
    password: "stevenK!ng",
    phone: "01622334466",
    address: "Gopalganj",
    isAdmin: true,
  },
  {
    name: "Nicole Green",
    email: "nicole.green@nature.org",
    password: "nicoleGrn",
    phone: "01733445577",
    address: "Madaripur",
  },
];
